"""
RZ Automedata - Keyword Research UI
Premium keyword research page with Adobe Stock integration.
Displays search results, competition levels, and opportunity analysis.
Related keywords are generated by AI using the user's configured provider.
Mixed into the main RZAutomedata class.
"""

import customtkinter as ctk
import threading
import webbrowser

from ui.theme import COLORS
from core.keyword_scraper import (
    search_adobe_stock, analyze_keywords,
    generate_related_keywords_ai, format_number,
    ASSET_TYPE_LABELS, ASSET_TYPE_FILTERS,
    _get_competition_level, _get_opportunity_level,
)


class KeywordResearchMixin:
    """Mixin that adds keyword research page methods to the main app."""

    def _build_keyword_research_page(self, parent):
        """Build the keyword research page."""
        self.kr_page_frame = ctk.CTkFrame(parent, fg_color="transparent")
        # Don't grid yet — controlled by nav

        # Main layout: left panel (search + results), right panel (related keywords)
        self.kr_page_frame.grid_rowconfigure(0, weight=1)
        self.kr_page_frame.grid_columnconfigure(0, weight=3)
        self.kr_page_frame.grid_columnconfigure(1, weight=2)

        # ═══════════════════════════════════════════════════════════════════════
        # LEFT PANEL — Search + Results Table
        # ═══════════════════════════════════════════════════════════════════════
        left_panel = ctk.CTkFrame(
            self.kr_page_frame, fg_color=COLORS["bg_dark"], corner_radius=12,
            border_width=1, border_color=COLORS["border"]
        )
        left_panel.grid(row=0, column=0, sticky="nsew", padx=(8, 6), pady=(8, 12))
        left_panel.grid_rowconfigure(3, weight=1)
        left_panel.grid_columnconfigure(0, weight=1)

        # ── Header ──
        header = ctk.CTkFrame(left_panel, fg_color=COLORS["bg_card"], corner_radius=0, height=48)
        header.grid(row=0, column=0, sticky="ew")
        header.grid_propagate(False)

        ctk.CTkLabel(
            header, text="🔍  Keyword Research — Adobe Stock",
            font=ctk.CTkFont(size=16, weight="bold"), text_color=COLORS["neon_blue"]
        ).pack(side="left", padx=16, pady=10)

        ctk.CTkLabel(
            header, text="US Region",
            font=ctk.CTkFont(size=10), text_color=COLORS["text_muted"],
            fg_color=COLORS["bg_input"], corner_radius=4
        ).pack(side="right", padx=16, pady=10)

        # Glow line under header
        ctk.CTkFrame(left_panel, fg_color=COLORS["neon_blue"], height=1, corner_radius=0).grid(
            row=0, column=0, sticky="sew")

        # ── Search Bar ──
        search_frame = ctk.CTkFrame(left_panel, fg_color="transparent")
        search_frame.grid(row=1, column=0, sticky="ew", padx=16, pady=(12, 4))
        search_frame.grid_columnconfigure(1, weight=1)

        # Asset type selector
        type_frame = ctk.CTkFrame(search_frame, fg_color="transparent")
        type_frame.grid(row=0, column=0, columnspan=3, sticky="w", pady=(0, 8))

        ctk.CTkLabel(
            type_frame, text="Asset Type:",
            font=ctk.CTkFont(size=11, weight="bold"), text_color=COLORS["text_secondary"]
        ).pack(side="left", padx=(0, 8))

        self.kr_asset_type_var = ctk.StringVar(value="all")
        asset_types = [("🖼  All", "all"), ("📷  Photos", "photo"), ("🎨  Vectors", "vector"), ("🎬  Videos", "video")]
        
        self._kr_type_buttons = {}
        for label, value in asset_types:
            btn = ctk.CTkButton(
                type_frame, text=label, width=90, height=28, corner_radius=6,
                font=ctk.CTkFont(size=11, weight="bold"),
                fg_color=COLORS["accent_blue"] if value == "all" else COLORS["bg_input"],
                hover_color=COLORS["neon_blue"],
                text_color="white" if value == "all" else COLORS["text_secondary"],
                border_width=1, border_color=COLORS["border"],
                command=lambda v=value: self._kr_select_asset_type(v)
            )
            btn.pack(side="left", padx=2)
            self._kr_type_buttons[value] = btn

        # Search input row
        ctk.CTkLabel(
            search_frame, text="🔍",
            font=ctk.CTkFont(size=18), text_color=COLORS["neon_blue"]
        ).grid(row=1, column=0, padx=(0, 6))

        self.kr_search_entry = ctk.CTkEntry(
            search_frame, placeholder_text="Enter keywords to research (e.g., coffee latte, sunset beach)...",
            fg_color=COLORS["bg_input"], border_color=COLORS["border"],
            text_color=COLORS["text_primary"], placeholder_text_color=COLORS["text_muted"],
            font=ctk.CTkFont(size=13), height=38, corner_radius=8
        )
        self.kr_search_entry.grid(row=1, column=1, sticky="ew", padx=(0, 8))
        self.kr_search_entry.bind("<Return>", lambda e: self._kr_start_analysis())

        self.kr_analyze_btn = ctk.CTkButton(
            search_frame, text="🚀  Analyze", command=self._kr_start_analysis,
            fg_color=COLORS["accent_blue"], hover_color=COLORS["neon_blue"],
            text_color="white", font=ctk.CTkFont(size=13, weight="bold"),
            width=120, height=38, corner_radius=8
        )
        self.kr_analyze_btn.grid(row=1, column=2)

        # ── Progress Bar (hidden by default) ──
        self.kr_progress_frame = ctk.CTkFrame(left_panel, fg_color="transparent")
        self.kr_progress_frame.grid(row=2, column=0, sticky="ew", padx=16, pady=(4, 0))

        self.kr_progress_label = ctk.CTkLabel(
            self.kr_progress_frame, text="",
            font=ctk.CTkFont(size=11), text_color=COLORS["text_secondary"]
        )
        self.kr_progress_label.pack(side="left")

        self.kr_progress_bar = ctk.CTkProgressBar(
            self.kr_progress_frame, height=8, corner_radius=4,
            fg_color=COLORS["bg_input"], progress_color=COLORS["neon_blue"]
        )
        self.kr_progress_bar.set(0)
        self.kr_progress_bar.pack(side="right", fill="x", expand=True, padx=(8, 0))
        self.kr_progress_frame.grid_remove()  # Hide initially

        # ── Results Table ──
        self.kr_results_container = ctk.CTkFrame(
            left_panel, fg_color="transparent"
        )
        self.kr_results_container.grid(row=3, column=0, sticky="nsew", padx=8, pady=(4, 8))
        self.kr_results_container.grid_rowconfigure(1, weight=1)
        self.kr_results_container.grid_columnconfigure(0, weight=1)

        # Build empty state
        self._kr_show_empty_state()

        # ═══════════════════════════════════════════════════════════════════════
        # RIGHT PANEL — Related Keywords (AI-powered)
        # ═══════════════════════════════════════════════════════════════════════
        right_panel = ctk.CTkFrame(
            self.kr_page_frame, fg_color=COLORS["bg_dark"], corner_radius=12,
            border_width=1, border_color=COLORS["border"]
        )
        right_panel.grid(row=0, column=1, sticky="nsew", padx=(6, 12), pady=(8, 12))
        right_panel.grid_rowconfigure(1, weight=1)
        right_panel.grid_columnconfigure(0, weight=1)

        # ── Related Keywords Header ──
        related_header = ctk.CTkFrame(right_panel, fg_color=COLORS["bg_card"], corner_radius=0, height=48)
        related_header.grid(row=0, column=0, sticky="ew")
        related_header.grid_propagate(False)
        ctk.CTkLabel(
            related_header, text="🤖  Related Keywords (AI)",
            font=ctk.CTkFont(size=14, weight="bold"), text_color=COLORS["warning"]
        ).pack(side="left", padx=16, pady=10)

        self.kr_related_status = ctk.CTkLabel(
            related_header, text="",
            font=ctk.CTkFont(size=9), text_color=COLORS["text_muted"]
        )
        self.kr_related_status.pack(side="right", padx=(0, 8))

        self.kr_copy_all_related_btn = ctk.CTkButton(
            related_header, text="📋 Copy All", width=90, height=28, corner_radius=6,
            font=ctk.CTkFont(size=10, weight="bold"),
            fg_color=COLORS["accent_blue"], hover_color=COLORS["neon_blue"],
            text_color="white",
            command=self._kr_copy_all_related
        )
        self.kr_copy_all_related_btn.pack(side="right", padx=8, pady=8)

        ctk.CTkFrame(right_panel, fg_color=COLORS["warning"], height=1, corner_radius=0).grid(
            row=0, column=0, sticky="sew")

        # Related keywords scroll area (full height)
        self.kr_related_scroll = ctk.CTkScrollableFrame(
            right_panel, fg_color="transparent",
            scrollbar_button_color=COLORS["accent_blue"],
            scrollbar_button_hover_color=COLORS["neon_blue"]
        )
        self.kr_related_scroll.grid(row=1, column=0, sticky="nsew", padx=4, pady=(4, 8))

        self.kr_related_placeholder = ctk.CTkLabel(
            self.kr_related_scroll,
            text="🤖 AI will suggest 20 related keywords\nusing your configured AI provider\n\nSearch a keyword first to generate",
            font=ctk.CTkFont(size=12), text_color=COLORS["text_muted"],
            justify="center"
        )
        self.kr_related_placeholder.pack(pady=60)

        # ── State ──
        self._kr_analyzing = False
        self._kr_stop_event = threading.Event()
        self._kr_results = []
        self._kr_related_keywords = []

    # ─── Asset Type Selector ──────────────────────────────────────────────────

    def _kr_select_asset_type(self, asset_type):
        """Handle asset type button click."""
        self.kr_asset_type_var.set(asset_type)
        for val, btn in self._kr_type_buttons.items():
            if val == asset_type:
                btn.configure(
                    fg_color=COLORS["accent_blue"],
                    text_color="white"
                )
            else:
                btn.configure(
                    fg_color=COLORS["bg_input"],
                    text_color=COLORS["text_secondary"]
                )

    # ─── Empty State ──────────────────────────────────────────────────────────

    def _kr_show_empty_state(self):
        """Show empty state in results area."""
        # Clear results container
        for widget in self.kr_results_container.winfo_children():
            widget.destroy()

        empty_frame = ctk.CTkFrame(self.kr_results_container, fg_color="transparent")
        empty_frame.pack(expand=True, fill="both")

        inner = ctk.CTkFrame(empty_frame, fg_color="transparent")
        inner.place(relx=0.5, rely=0.4, anchor="center")

        ctk.CTkLabel(
            inner, text="🔍",
            font=ctk.CTkFont(size=48)
        ).pack(pady=(0, 8))

        ctk.CTkLabel(
            inner, text="Keyword Research",
            font=ctk.CTkFont(size=20, weight="bold"), text_color=COLORS["text_primary"]
        ).pack()

        ctk.CTkLabel(
            inner, text="Enter keywords separated by commas to analyze\ntheir competition and opportunity on Adobe Stock",
            font=ctk.CTkFont(size=12), text_color=COLORS["text_muted"],
            justify="center"
        ).pack(pady=(4, 16))

        # Quick tips
        tips_frame = ctk.CTkFrame(inner, fg_color=COLORS["bg_card"], corner_radius=10,
                                   border_width=1, border_color=COLORS["border"])
        tips_frame.pack(padx=20, fill="x")

        ctk.CTkLabel(
            tips_frame, text="💡 Tips",
            font=ctk.CTkFont(size=12, weight="bold"), text_color=COLORS["neon_blue"]
        ).pack(padx=12, pady=(8, 4), anchor="w")

        tips = [
            "• Use commas to research multiple keywords at once",
            "• 🟢 HIGH opportunity = less competition, easier to rank",
            "• 🔴 LOW opportunity = very saturated market",
            "• Select asset type (Photo/Vector/Video) for specific results",
            "• Click keyword rows to open Adobe Stock search page",
            "• AI generates related keywords using your configured provider",
        ]
        for tip in tips:
            ctk.CTkLabel(
                tips_frame, text=tip,
                font=ctk.CTkFont(size=10), text_color=COLORS["text_secondary"],
                justify="left"
            ).pack(padx=12, pady=1, anchor="w")

        ctk.CTkLabel(tips_frame, text="").pack(pady=4)  # Spacer

    # ─── Start Analysis ───────────────────────────────────────────────────────

    def _kr_start_analysis(self):
        """Start keyword analysis."""
        if self._kr_analyzing:
            self._kr_stop_event.set()
            self.kr_analyze_btn.configure(text="🚀  Analyze", fg_color=COLORS["accent_blue"])
            self._kr_analyzing = False
            return

        query = self.kr_search_entry.get().strip()
        if not query:
            return

        # Parse keywords (comma separated)
        keywords = [kw.strip() for kw in query.split(",") if kw.strip()]
        if not keywords:
            return

        asset_type = self.kr_asset_type_var.get()
        self._kr_analyzing = True
        self._kr_stop_event.clear()
        self._kr_results = []

        # Update UI
        self.kr_analyze_btn.configure(text="⏹  Stop", fg_color=COLORS["error"])
        self.kr_progress_frame.grid()
        self.kr_progress_bar.set(0)
        self.kr_progress_label.configure(text=f"Analyzing 0/{len(keywords)}...")

        # Clear previous results
        self._kr_build_results_table(keywords)

        # Clear related keywords list for Copy All
        self._kr_related_keywords = []

        # Clear related keywords area
        for w in self.kr_related_scroll.winfo_children():
            w.destroy()
        ctk.CTkLabel(
            self.kr_related_scroll,
            text="⏳ Waiting for AI to generate related keywords...",
            font=ctk.CTkFont(size=11), text_color=COLORS["text_muted"],
            justify="center"
        ).pack(pady=30)
        self.kr_related_status.configure(text="generating...")

        # Start analysis thread
        def _worker():
            results = analyze_keywords(
                keywords, asset_type=asset_type,
                on_progress=lambda c, t: self.after(0, self._kr_on_progress, c, t),
                on_keyword_done=lambda r: self.after(0, self._kr_on_keyword_done, r),
                stop_event=self._kr_stop_event,
            )
            self.after(0, self._kr_on_analysis_complete, results)

        threading.Thread(target=_worker, daemon=True).start()

        # Fetch AI-generated related keywords using saved provider settings
        def _fetch_related():
            # Get AI provider settings from the main app
            provider_name = self.provider_var.get() if hasattr(self, 'provider_var') else None
            model = self.model_var.get() if hasattr(self, 'model_var') else None
            
            # Get API key from saved keys dict
            api_key = None
            if provider_name and hasattr(self, 'api_keys'):
                api_key = self.api_keys.get(provider_name, "")
            if not api_key and hasattr(self, 'api_key_entry'):
                api_key = self.api_key_entry.get().strip()
            
            if not provider_name or not model or not api_key:
                self.after(0, self._kr_show_related_no_api)
                return
            
            self.after(0, lambda: self.kr_related_status.configure(
                text=f"using {provider_name} / {model}"
            ))
            
            related_results = generate_related_keywords_ai(
                keywords[0], asset_type=asset_type,
                provider_name=provider_name, model=model, api_key=api_key,
                stop_event=self._kr_stop_event,
                on_keyword_done=lambda r: self.after(0, self._kr_on_related_keyword_done, r),
            )
            self.after(0, self._kr_on_related_complete, keywords[0], related_results)

        threading.Thread(target=_fetch_related, daemon=True).start()

    # ─── Build Results Table ──────────────────────────────────────────────────

    def _kr_build_results_table(self, keywords):
        """Build the results table shell."""
        for widget in self.kr_results_container.winfo_children():
            widget.destroy()

        # Table header
        table_header = ctk.CTkFrame(
            self.kr_results_container, fg_color=COLORS["table_header"],
            height=36, corner_radius=0
        )
        table_header.grid(row=0, column=0, sticky="ew")
        table_header.grid_propagate(False)

        col_config = [
            ("#", 36, 0),
            ("Keyword", 0, 3),
            ("Total Results", 120, 0),
            ("Competition", 110, 0),
            ("Opportunity", 110, 0),
            ("", 40, 0),  # Link
        ]

        for i, (name, width, weight) in enumerate(col_config):
            table_header.grid_columnconfigure(i, weight=weight, minsize=width if width else 100)
            cell = ctk.CTkFrame(table_header, fg_color="transparent")
            cell.grid(row=0, column=i, sticky="nsew")
            cell.grid_rowconfigure(0, weight=1)
            cell.grid_columnconfigure(0, weight=1)
            if i > 0:
                ctk.CTkFrame(cell, fg_color=COLORS["table_border"], width=1).place(
                    x=0, rely=0.1, relheight=0.8, anchor="nw")
            ctk.CTkLabel(
                cell, text=name,
                font=ctk.CTkFont(size=11, weight="bold"),
                text_color=COLORS["neon_blue"]
            ).grid(row=0, column=0, padx=6, pady=6)

        # Glow under header
        ctk.CTkFrame(
            self.kr_results_container, fg_color=COLORS["neon_blue"], height=1, corner_radius=0
        ).grid(row=0, column=0, sticky="sew")

        # Scroll body
        self.kr_results_scroll = ctk.CTkScrollableFrame(
            self.kr_results_container, fg_color=COLORS["bg_dark"],
            scrollbar_button_color=COLORS["accent_blue"],
            scrollbar_button_hover_color=COLORS["neon_blue"]
        )
        self.kr_results_scroll.grid(row=1, column=0, sticky="nsew")

        for i, (_, width, weight) in enumerate(col_config):
            self.kr_results_scroll.grid_columnconfigure(i, weight=weight, minsize=width if width else 100)

        # Pre-create rows with loading state
        self._kr_result_rows = {}
        for idx, kw in enumerate(keywords):
            self._kr_create_result_row(idx, kw)

    def _kr_create_result_row(self, idx, keyword):
        """Create a single result row in loading state."""
        row_bg = COLORS["table_row_even"] if idx % 2 == 0 else COLORS["table_row_odd"]

        row_frame = ctk.CTkFrame(
            self.kr_results_scroll, fg_color=row_bg, corner_radius=0, height=44
        )
        row_frame.grid(row=idx, column=0, columnspan=6, sticky="nsew", pady=(0, 1))
        row_frame.grid_propagate(False)
        row_frame.grid_rowconfigure(0, weight=1)

        col_config = [
            (36, 0), (0, 3), (120, 0), (110, 0), (110, 0), (40, 0)
        ]
        for i, (width, weight) in enumerate(col_config):
            row_frame.grid_columnconfigure(i, weight=weight, minsize=width if width else 100)

        # Col 0: Number
        no_cell = ctk.CTkFrame(row_frame, fg_color="transparent")
        no_cell.grid(row=0, column=0, sticky="nsew")
        no_cell.grid_rowconfigure(0, weight=1)
        no_cell.grid_columnconfigure(0, weight=1)
        ctk.CTkLabel(
            no_cell, text=str(idx + 1),
            font=ctk.CTkFont(size=11, weight="bold"), text_color=COLORS["neon_blue"]
        ).grid(row=0, column=0)
        ctk.CTkFrame(no_cell, fg_color=COLORS["table_border"], width=1).place(
            relx=1.0, rely=0.05, relheight=0.9, anchor="ne")

        # Col 1: Keyword
        kw_cell = ctk.CTkFrame(row_frame, fg_color="transparent")
        kw_cell.grid(row=0, column=1, sticky="nsew")
        kw_cell.grid_rowconfigure(0, weight=1)
        kw_cell.grid_columnconfigure(0, weight=1)
        ctk.CTkLabel(
            kw_cell, text=keyword,
            font=ctk.CTkFont(size=12, weight="bold"), text_color=COLORS["text_primary"],
            anchor="w"
        ).grid(row=0, column=0, padx=10, sticky="w")
        ctk.CTkFrame(kw_cell, fg_color=COLORS["table_border"], width=1).place(
            relx=1.0, rely=0.05, relheight=0.9, anchor="ne")

        # Col 2: Total Results (loading)
        results_cell = ctk.CTkFrame(row_frame, fg_color="transparent")
        results_cell.grid(row=0, column=2, sticky="nsew")
        results_cell.grid_rowconfigure(0, weight=1)
        results_cell.grid_columnconfigure(0, weight=1)
        results_label = ctk.CTkLabel(
            results_cell, text="⏳",
            font=ctk.CTkFont(size=11), text_color=COLORS["text_muted"]
        )
        results_label.grid(row=0, column=0)
        ctk.CTkFrame(results_cell, fg_color=COLORS["table_border"], width=1).place(
            relx=1.0, rely=0.05, relheight=0.9, anchor="ne")

        # Col 3: Competition (loading)
        comp_cell = ctk.CTkFrame(row_frame, fg_color="transparent")
        comp_cell.grid(row=0, column=3, sticky="nsew")
        comp_cell.grid_rowconfigure(0, weight=1)
        comp_cell.grid_columnconfigure(0, weight=1)
        comp_label = ctk.CTkLabel(
            comp_cell, text="⏳",
            font=ctk.CTkFont(size=10, weight="bold"), text_color=COLORS["text_muted"]
        )
        comp_label.grid(row=0, column=0)
        ctk.CTkFrame(comp_cell, fg_color=COLORS["table_border"], width=1).place(
            relx=1.0, rely=0.05, relheight=0.9, anchor="ne")

        # Col 4: Opportunity (loading)
        opp_cell = ctk.CTkFrame(row_frame, fg_color="transparent")
        opp_cell.grid(row=0, column=4, sticky="nsew")
        opp_cell.grid_rowconfigure(0, weight=1)
        opp_cell.grid_columnconfigure(0, weight=1)
        opp_label = ctk.CTkLabel(
            opp_cell, text="⏳",
            font=ctk.CTkFont(size=10, weight="bold"), text_color=COLORS["text_muted"]
        )
        opp_label.grid(row=0, column=0)
        ctk.CTkFrame(opp_cell, fg_color=COLORS["table_border"], width=1).place(
            relx=1.0, rely=0.05, relheight=0.9, anchor="ne")

        # Col 5: Link button
        link_cell = ctk.CTkFrame(row_frame, fg_color="transparent")
        link_cell.grid(row=0, column=5, sticky="nsew")
        link_cell.grid_rowconfigure(0, weight=1)
        link_cell.grid_columnconfigure(0, weight=1)
        link_btn = ctk.CTkButton(
            link_cell, text="🔗", width=28, height=28, corner_radius=6,
            fg_color="transparent", hover_color=COLORS["bg_card_hover"],
            font=ctk.CTkFont(size=14),
            command=lambda kw=keyword: self._kr_open_adobe_stock(kw)
        )
        link_btn.grid(row=0, column=0)

        # Bottom border
        ctk.CTkFrame(row_frame, fg_color=COLORS["table_border"], height=1).place(
            relx=0, rely=1.0, relwidth=1.0, anchor="sw")

        # Store references
        self._kr_result_rows[keyword.strip().lower()] = {
            "row_frame": row_frame,
            "results_label": results_label,
            "comp_label": comp_label,
            "opp_label": opp_label,
        }

    # ─── Callbacks ────────────────────────────────────────────────────────────

    def _kr_on_progress(self, current, total):
        """Update progress bar."""
        self.kr_progress_bar.set(current / total)
        self.kr_progress_label.configure(text=f"Analyzing {current}/{total}...")

    def _kr_on_keyword_done(self, result):
        """Update a single keyword row with results."""
        kw_key = result["keyword"].strip().lower()
        row = self._kr_result_rows.get(kw_key)
        if not row:
            return

        total = result.get("total_results", -1)
        if total < 0:
            row["results_label"].configure(text="⚠️ Error", text_color=COLORS["error"])
            row["comp_label"].configure(text="N/A", text_color=COLORS["text_muted"])
            row["opp_label"].configure(text="N/A", text_color=COLORS["text_muted"])
            return

        # Update results
        row["results_label"].configure(
            text=format_number(total),
            text_color=COLORS["text_primary"],
            font=ctk.CTkFont(size=12, weight="bold")
        )

        # Update competition
        comp_text = f"{result['competition_icon']} {result['competition_level']}"
        row["comp_label"].configure(
            text=comp_text,
            text_color=result["competition_color"]
        )

        # Update opportunity
        opp_text = f"{result['opportunity_icon']} {result['opportunity_level']}"
        row["opp_label"].configure(
            text=opp_text,
            text_color=result["opportunity_color"]
        )

    def _kr_on_analysis_complete(self, results):
        """Called when all keywords are analyzed."""
        self._kr_analyzing = False
        self._kr_results = results
        self.kr_analyze_btn.configure(text="🚀  Analyze", fg_color=COLORS["accent_blue"])
        self.kr_progress_frame.grid_remove()


    # ─── Related Keywords (AI-Powered) ────────────────────────────────────────

    def _kr_copy_all_related(self):
        """Copy all related keywords as comma-separated list."""
        if not self._kr_related_keywords:
            return
        text = ", ".join(self._kr_related_keywords)
        self.clipboard_clear()
        self.clipboard_append(text)
        self.kr_copy_all_related_btn.configure(text="✅ Copied!")
        self.after(1500, lambda: self.kr_copy_all_related_btn.configure(text="📋 Copy All"))

    def _kr_copy_keyword(self, keyword, btn):
        """Copy a single keyword to clipboard."""
        self.clipboard_clear()
        self.clipboard_append(keyword)
        btn.configure(text="✅")
        self.after(1000, lambda: btn.configure(text="📋"))

    def _kr_show_related_no_api(self):
        """Show message when no AI provider is configured."""
        for w in self.kr_related_scroll.winfo_children():
            w.destroy()
        
        self.kr_related_status.configure(text="⚠️ no API key")
        
        msg_frame = ctk.CTkFrame(self.kr_related_scroll, fg_color="transparent")
        msg_frame.pack(expand=True, fill="both")
        
        inner = ctk.CTkFrame(msg_frame, fg_color="transparent")
        inner.place(relx=0.5, rely=0.35, anchor="center")
        
        ctk.CTkLabel(
            inner, text="⚠️",
            font=ctk.CTkFont(size=32)
        ).pack(pady=(0, 8))
        
        ctk.CTkLabel(
            inner, text="No AI Provider Configured",
            font=ctk.CTkFont(size=14, weight="bold"), text_color=COLORS["warning"]
        ).pack()
        
        ctk.CTkLabel(
            inner, text="To get AI-generated related keywords,\nconfigure your API key in the Metadata page\n(Settings → AI Provider)",
            font=ctk.CTkFont(size=11), text_color=COLORS["text_muted"],
            justify="center"
        ).pack(pady=(4, 0))

    def _kr_on_related_keyword_done(self, result):
        """Called when a single related keyword lookup is done — add card to related panel."""
        # Remove placeholder on first result
        for w in self.kr_related_scroll.winfo_children():
            if isinstance(w, ctk.CTkLabel) and "Waiting" in str(w.cget("text")):
                w.destroy()
                break
        
        # Track keyword for Copy All
        kw = result.get("keyword", "")
        if kw and kw not in self._kr_related_keywords:
            self._kr_related_keywords.append(kw)

        # Create card in the related scroll area
        self._kr_create_related_card(result)

    def _kr_on_related_complete(self, original_keyword, related_results):
        """Called when all related keywords are analyzed."""
        if not related_results:
            # Clear and show no results
            for w in self.kr_related_scroll.winfo_children():
                w.destroy()
            ctk.CTkLabel(
                self.kr_related_scroll,
                text="No related keywords found",
                font=ctk.CTkFont(size=11), text_color=COLORS["text_muted"]
            ).pack(pady=30)
            self.kr_related_status.configure(text="done")
            return
        
        self.kr_related_status.configure(text=f"✅ {len(related_results)} keywords")

    def _kr_create_related_card(self, result):
        """Create a card for a related keyword in the related keywords panel."""
        card = ctk.CTkFrame(
            self.kr_related_scroll, fg_color=COLORS["bg_card"], corner_radius=8,
            border_width=1, border_color=COLORS["border"]
        )
        card.pack(fill="x", padx=4, pady=2)

        # Top row: keyword + results count
        top = ctk.CTkFrame(card, fg_color="transparent")
        top.pack(fill="x", padx=10, pady=(6, 2))

        ctk.CTkLabel(
            top, text=f'🔗 "{result["keyword"]}"',
            font=ctk.CTkFont(size=11, weight="bold"), text_color=COLORS["text_primary"]
        ).pack(side="left")

        total = result.get("total_results", -1)
        if total >= 0:
            ctk.CTkLabel(
                top, text=format_number(total),
                font=ctk.CTkFont(size=11, weight="bold"), text_color=COLORS["neon_blue"]
            ).pack(side="right")
        else:
            ctk.CTkLabel(
                top, text="Error",
                font=ctk.CTkFont(size=10), text_color=COLORS["error"]
            ).pack(side="right")

        # Bottom row: competition + opportunity + copy + link
        bottom = ctk.CTkFrame(card, fg_color="transparent")
        bottom.pack(fill="x", padx=10, pady=(0, 6))

        if total >= 0:
            ctk.CTkLabel(
                bottom,
                text=f" {result['competition_icon']} {result['competition_level']} ",
                font=ctk.CTkFont(size=9, weight="bold"),
                text_color=result["competition_color"],
                fg_color=COLORS["bg_input"], corner_radius=4
            ).pack(side="left", padx=(0, 4))

            ctk.CTkLabel(
                bottom,
                text=f" {result['opportunity_icon']} {result['opportunity_level']} ",
                font=ctk.CTkFont(size=9, weight="bold"),
                text_color=result["opportunity_color"],
                fg_color=COLORS["bg_input"], corner_radius=4
            ).pack(side="left")

        # Open link button
        ctk.CTkButton(
            bottom, text="🔗", width=24, height=22, corner_radius=4,
            fg_color="transparent", hover_color=COLORS["bg_card_hover"],
            font=ctk.CTkFont(size=12),
            command=lambda kw=result["keyword"]: self._kr_open_adobe_stock(kw)
        ).pack(side="right")

        # Copy button
        copy_btn = ctk.CTkButton(
            bottom, text="📋", width=24, height=22, corner_radius=4,
            fg_color="transparent", hover_color=COLORS["bg_card_hover"],
            font=ctk.CTkFont(size=12),
        )
        copy_btn.configure(command=lambda kw=result["keyword"], b=copy_btn: self._kr_copy_keyword(kw, b))
        copy_btn.pack(side="right", padx=(0, 4))

    # ─── Utilities ────────────────────────────────────────────────────────────

    def _kr_open_adobe_stock(self, keyword):
        """Open Adobe Stock search page for a keyword."""
        import urllib.parse
        asset_type = self.kr_asset_type_var.get()
        type_filters = ASSET_TYPE_FILTERS.get(asset_type, {})
        encoded_kw = urllib.parse.quote_plus(keyword.strip())
        filter_str = ""
        for k, v in type_filters.items():
            filter_str += f"&{k}={v}"
        url = f"https://stock.adobe.com/search?k={encoded_kw}{filter_str}"
        webbrowser.open(url)
